//
//  FoodList.swift
//  SCD Food List
//
//  Created by George McLellan on 23/8/20.
//  Copyright © 2020 George McLellan. All rights reserved.
//

import Foundation

var FoodListData: [Food] = [
    Food(name: "Acorn squash", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Agar-agar",allowed: .illegal, foodGroup: .miscellaneous, description: "Contains polysaccharides.  See wikipedia"),
    Food(name: "Agave syrup", allowed: .illegal, foodGroup: .sweeteners),
    Food(name: "Algae", allowed: .illegal, foodGroup: .miscellaneous, description: "We do not use algae (Spirulina) because IBD involves the immune system and algae can aggravate an already disturbed immune system."),
    Food(name: "Allspice", allowed: .legal, foodGroup: .spices, description: "As long as you're just using Allspice as a cooking spice, it's allowed. Don't use the oil."),
    Food(name: "Almond butter", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Almond butter with no sugar added is allowed."),
    Food(name: "Almond milk", allowed: .legal, foodGroup: .drinks, description: "May be tried after being on diet for 6 months."),
    Food(name: "Almond oil", allowed: .legal, foodGroup: .fatsAndOils),
    Food(name: "Almonds", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating. Nuts should only be used as nut flour, in recipes, until diarrhea has subsided."),
    Food(name: "Aloe vera", allowed: .illegal, foodGroup: .miscellaneous, description: "It contains mucilaginous polysaccharides as well as increasing the release of tumor necrosis factor which is associated with IBD inflammation and increased immune stimulation."),
    Food(name: "Amaranth flour", allowed: .illegal, foodGroup: .starch, description: "Amaranth is a grain substitute, contains starches and so is not allowed."),
    Food(name: "Anchovies", allowed: .legal, foodGroup: .animalProteins),
    Food(name: "Apple cider", allowed: .legal, foodGroup: .drinks, description: "It is brown and not clear as apple juice is. It should be just straight pressed apples. It is usually pasteurized in order to kill bacteria. Cider should be diluted with water before drinking."),
    Food(name: "Apple juice", allowed: .illegal, foodGroup: .drinks, description: "Apple juice usually has sugar added during processing. Apple cider is allowed. It should be brown and not clear as apple juice is. Cider should be diluted with water before drinking."),
    Food(name: "Apples", allowed: .legal, foodGroup: .fruit),
    Food(name: "Apricots", allowed: .legal, foodGroup: .fruit),
    Food(name: "Arrowroot", allowed: .illegal, foodGroup: .starch, description: "It is a mucilaginous herb. Mucilaginous herbs are loaded with starch. This starch is food for the pathogens that the SCD™ is designed to starve out."),
    Food(name: "Artichoke (French)", allowed: .legal, foodGroup: .vegetables, description: "They are the green artichokes that you steam, then dip the leaves in lemon butter and scrape off with your teeth. They have edible hearts and an inedible choke."),
    Food(name: "Artichokes (Jerusalem)", allowed: .illegal, foodGroup: .vegetables, description: "They are actually a tuber, and are not legal."),
    Food(name: "Ascorbic acid", allowed: .legal, foodGroup: .miscellaneous, description: "Should be nothing but vitamin C."),
    Food(name: "Asiago cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Asparagus", allowed: .legal, foodGroup: .vegetables, description: "Fresh or frozen is allowed. Canned vegetables are not allowed."),
    Food(name: "Aspartame", allowed: .legal, foodGroup: .sweeteners, description: "When symptom free, one aspartame sweetened soft drink per week is allowed - Elaine. But see Aspartame in Knowledge Base of BTVC website."),
    Food(name: "Aspartic acid", allowed: .legal, foodGroup: .miscellaneous),
    Food(name: "Astragalus", allowed: .illegal, foodGroup: .herbs, description: "contains polysaccharides"),
    Food(name: "Avocado oil", allowed: .legal, foodGroup: .fatsAndOils, description: "Good for mayonaise and salad dressings but might not withstand heat very well"),
    Food(name: "Avocados", allowed: .legal, foodGroup: .fruit),
    Food(name: "Bacon", allowed: .warning, foodGroup: .animalProteins, description: "Smoked bacon that has been fried very crisply is allowed once per week. There are sugar-free bacons available and if you are able to find a source of sugar-free bacon, you do not have to limit your consumption to once per week. Usually the low sodium varieties do not contain sugar but check the labels carefully."),
    Food(name: "Baker's yeast", allowed: .illegal, foodGroup: .miscellaneous, description: "Saccharamyces cerevisae is baker's yeast and is illegal."),
    Food(name: "Baking powder", allowed: .illegal, foodGroup: .miscellaneous, description: "Has starch as an ingredient, (usually corn starch) and other illegals to make it rise better."),
    Food(name: "Baking soda",allowed: .legal, foodGroup: .miscellaneous),
    Food(name: "Balsamic vinegar", allowed: .warning, foodGroup: .miscellaneous, description: "It's not that balsamic vinegar is illegal, it's that what you can get in the store isn't really balsamic vinegar and most have sugar added to them so Elaine doesn't allow it. You can make your own legal substitute though see scdrecipe.com"),
    Food(name: "Bananas", allowed: .legal, foodGroup: .fruit, description: "They must be ripe with black spots on the skin."),
    Food(name: "Bark tea", allowed: .illegal, foodGroup: .drinks, description: "Bark tea (Pau d'Arco) contains steroidal saponins and is both an immune booster and a laxative."),
    Food(name: "Barley", allowed: .illegal, foodGroup: .grains),
    Food(name: "Basil",allowed: .legal, foodGroup: .herbs),
    Food(name: "Bay leaf",allowed: .legal, foodGroup: .herbs),
    Food(name: "Bean flour", allowed: .illegal, foodGroup: .legumes, description: "Do not use ready made flours made from beans or lentils as they probably weren't soaked prior to grinding to bean flour."),
    Food(name: "Bean sprouts", allowed: .illegal, foodGroup: .vegetables),
    Food(name: "Bee pollen", allowed: .illegal, foodGroup: .miscellaneous, description: "Pollen is irritating to a damaged gut. Clear, pure, pasteurized honey is okay. Cloudy honey (still containing the pollen) should be avoided."),
    Food(name: "Beef", allowed: .legal, foodGroup: .animalProteins, description: "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
    Food(name: "Beer", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Beets", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Berries", allowed: .legal, foodGroup: .fruit, description: "Berries of all kinds are legal."),
    Food(name: "Bhindi", allowed: .illegal, foodGroup: .vegetables, description: "No okra (bhindi) or drumsticks, since they are a mucilaginous food, they are illegal."),
    Food(name: "Bitter gourd", allowed: .illegal, foodGroup: .vegetables),
    //        Food(name: "Black azuki bean", allowed: .illegal, foodGroup: .legumes, description: "Aka: black adzuki, black aduki, asuki"),
    Food(name: "Black beans", allowed: .legal, foodGroup: .legumes, description: "May be tried when symptom free. Dried legumes must be prepared according to the instructions in the Breaking the Vicious Cycle book."),
    Food(name: "Black eye beans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Black radish", allowed: .legal, foodGroup: .vegetables, description: "It is very fibrous, so go slowly and be careful."),
    Food(name: "Blue cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Bok choy", allowed: .legal, foodGroup: .vegetables, description: "Bok Choy is much like cabbage and is legal but you should not use a member of the cabbage family until you are well on your way to getting better. In other words, do not use if you still have diarrhea and gas."),
    Food(name: "Bologna", allowed: .illegal, foodGroup: .animalProteins),
    Food(name: "Bouillon cubes", allowed: .illegal, foodGroup: .miscellaneous, description: "Bouillon cubes and instant soup bases are not permitted."),
    Food(name: "Bourbon", allowed: .legal, foodGroup: .drinks, description: "Only have it occasionally."),
    Food(name: "Brandy", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Brazil nuts", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
    Food(name: "Brick cheese", allowed: .legal, foodGroup: .dairy, description: "May be used freely."),
    Food(name: "Brie cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Broccoli", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Brussels sprouts", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Buckwheat", allowed: .illegal, foodGroup: .grains),
    Food(name: "Bulgur", allowed: .illegal, foodGroup: .grains),
    Food(name: "Burdock root", allowed: .illegal, foodGroup: .vegetables, description: "It contains inulin (FOS) and mucilage."),
    Food(name: "Butter", allowed: .legal, foodGroup: .dairy),
    Food(name: "Butter beans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Buttermilk", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Butternut squash", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Cabbage", allowed: .legal, foodGroup: .vegetables, description: "You should not use a member of the cabbage family until you are well on your way to getting better. In other words, do not use if you still have diarrhea and gas."),
    Food(name: "Camembert cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Canellini beans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Canned fish", allowed: .legal, foodGroup: .animalProteins, description: "Canned in oil or water is acceptable but check the labels carefully. Do not buy products containing \"broth\". Usually, the low sodium varieties do not contain \"broth\"."),
    Food(name: "Canned fruits", allowed: .illegal, foodGroup: .fruit, description: "Fruits canned in their own juice are allowed."),
    Food(name: "Canned vegetables", allowed: .illegal, foodGroup: .vegetables, description: "There are no canned vegetables permitted, they must either be fresh or frozen."),
    Food(name: "Canola oil", allowed: .warning, foodGroup: .fatsAndOils, description: "Legal, but not recommended. Highly processed and inflammatory oil."),
    Food(name: "Cantaloupe", allowed: .legal, foodGroup: .fruit),
    Food(name: "Capers", allowed: .legal, foodGroup: .miscellaneous),
    Food(name: "Carob", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Carrageenan", allowed: .illegal, foodGroup: .miscellaneous, description: "Carrageenan is seaweed and high in polysaccharides, therefore illegal."),
    Food(name: "Carrots", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Cashews", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
    Food(name: "Cauliflower", allowed: .legal, foodGroup: .vegetables, description: "Cauliflower is sometimes hard to digest and should be tried cautiously after some progress has been made on the diet."),
    Food(name: "Celeriac / celery root", allowed: .legal, foodGroup: .vegetables, description: "However, you should go slow and be careful. It is very fibrous, even if it doesn't seem so when you steam it and mash it."),
    Food(name: "Celery", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Cellulose (in supplements)", allowed: .legal, foodGroup: .miscellaneous, description: "Cellulose in your supplements is okay and virtually impossible to avoid."),
    Food(name: "Cellulose gum", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Cereals", allowed: .illegal, foodGroup: .grains, description: "However for a hot cereal see scdrecipe.com"),
    Food(name: "Chard", allowed: .legal, foodGroup: .vegetables, description: "Chard (red, green, rainbow and swiss). Chard is similar to spinach/celery so it is legal. It also reminds me a bit of the cabbage family so use with caution if gas is still a problem - Elaine"),
    Food(name: "Cheddar cheese", allowed: .legal, foodGroup: .dairy, description: "May be used freely."),
    Food(name: "Cheese", allowed: .legal, foodGroup: .dairy, description: "If a cheese is not a processed cheese (manufactured) but is a cheese that has had a bacterial culture involved with its production and is aged at least 30 days. Elaine says its OK."),
    Food(name: "Cherimoya", allowed: .legal, foodGroup: .fruit, description: "Also known as custard apple or sharifa."),
    Food(name: "Cherries", allowed: .legal, foodGroup: .fruit),
    Food(name: "Chestnut flour", allowed: .illegal, foodGroup: .nutsAndSeeds),
    Food(name: "Chestnuts", allowed: .legal, foodGroup: .nutsAndSeeds, description: "May be tried when symptom free. However, if you buy dried chestnuts, soak them and cook them until soft."),
    Food(name: "Chevre", allowed: .illegal, foodGroup: .dairy, description: "Chevre is illegal, but you can make a close approximation by dripping goat milk yoghurt. See BTVC website for recipe."),
    Food(name: "Chewing gum", allowed: .illegal, foodGroup: .miscellaneous, description: "Contains things like aspartame, maple or date sugar and other sugar substitutes which are illegal."),
    //        Food(name: "Chia seeds", allowed: .illegal, foodGroup: .nutsAndSeeds, description: "Mucilaginous"),
    Food(name: "Chick peas", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Chickory root", allowed: .illegal, foodGroup: .miscellaneous, description: "Chickory root is not legal. In my first book, I suggested that it might be used instead of coffee beans. I have since learned that it contains large amounts of fructooligosaccharides. - Elaine"),
    Food(name: "Chlorella", allowed: .illegal, foodGroup: .miscellaneous, description: "It is a blue-green algae similar to spirulina"),
    Food(name: "Chocolate", allowed: .illegal, foodGroup: .miscellaneous, description: "Dr. Haas advised not to use cocoa or chocolate and this still goes, it isn't just the sugar he was worried about."),
    Food(name: "Cilantro", allowed: .legal, foodGroup: .herbs),
    Food(name: "Cinnamon",allowed: .legal, foodGroup: .spices),
    Food(name: "Citric acid", allowed: .legal, foodGroup: .miscellaneous, description: "Citric acid as an additive is OK"),
    Food(name: "Club soda", allowed: .legal, foodGroup: .drinks),
    Food(name: "Cocoa powder", allowed: .illegal, foodGroup: .miscellaneous, description: "Dr. Haas advised not to use cocoa or chocolate and this still goes, it isn't just the sugar he was worried about."),
    Food(name: "Coconut", allowed: .legal, foodGroup: .fruit, description: "Fresh or unsweetened, shredded and flour are all legal."),
    Food(name: "Coconut milk", allowed: .legal, foodGroup: .miscellaneous, description: "May be tried after being on the diet for 6 months."),
    Food(name: "Coconut oil", allowed: .legal, foodGroup: .fatsAndOils, description: "Withstands heat well, good for frying/cooking"),
    Food(name: "Coffee (instant)", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Coffee (very weak)", allowed: .legal, foodGroup: .drinks),
    Food(name: "Colby cheese", allowed: .legal, foodGroup: .dairy, description: "May be used freely."),
    Food(name: "Collard greens", allowed: .legal, foodGroup: .vegetables, description: "Of the cabbage family, introduce late in diet."),
    Food(name: "Cordials", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Corn", allowed: .illegal, foodGroup: .vegetables),
    Food(name: "Corn oil", allowed: .legal, foodGroup: .fatsAndOils),
    Food(name: "Corn syrup", allowed: .illegal, foodGroup: .sweeteners),
    Food(name: "Cornstarch", allowed: .illegal, foodGroup: .starch),
    Food(name: "Cottage cheese",allowed: .illegal, foodGroup: .dairy),
    Food(name: "Courgette / zucchini", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Cranberry juice", allowed: .legal, foodGroup: .drinks, description: "We use Knudsen’s Just Cranberry juice, as it has been checked out and does not have sugar added. It can be found in most health food stores. Juice should be diluted with water before drinking. Since this is pure cranberry juice it is very tart, you may sweeten it with saccharine or honey or dilute it with legal apple cider instead of water."),
    Food(name: "Cream", allowed: .illegal,foodGroup: .dairy, description: "It is illegal as it contains lactose. Cream can be added to milk and then fermented to make SCD™ 24hr yoghurt as the lactsose will be used up in the fermentation. Cream has less lactose than milk and the more fat it contains the less lactose it has."),
    Food(name: "Cream cheese", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Cream of tartar", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Croscarmellose sodium", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Cucumbers", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Custard apple", allowed: .legal, foodGroup: .fruit, description: "Also known as sharifa or cherimoya"),
    Food(name: "Cyclamate", allowed: .legal, foodGroup: .sweeteners, description: "It is actually a better alternative than saccharine, if you can get it, because it has no aftertaste. But it's almost impossible to find by itself, and certainly not available in NA."),
    Food(name: "Date sugar", allowed: .illegal, foodGroup: .sweeteners, description: "May be tried after being on the diet for quite sometime and symptom free but it is not recommended."),
    Food(name: "Dates", allowed: .legal, foodGroup: .fruit, description: "Medjool and California dates are allowed. They must be loose and not have anything added."),
    Food(name: "Decaffeinated products", allowed: .illegal, foodGroup: .miscellaneous, description: "Decaffeinated products are not legal since the manufacturing process may introduce questionable ingredients or reactions."),
    Food(name: "Dextrose", allowed: .illegal, foodGroup: .sweeteners, description: "The problem with the dextrose and fructose which is being sold as a granulated form as well as the dextrose contained in commercial products is that it is not pure dextrose which should be the same as the single sugar glucose found in fruits and honey."),
    //        Food(name: "Diet soft drink, other sweetneer", allowed: .illegal, foodGroup: .drinks),
    //        Food(name: "Diet soft drink, saccharin", allowed: .warning, foodGroup: .drinks, description: "Allowed 2-3 a week on SCD™, avoid on GAPS"),
    //        Food(name: "Dill pickles", allowed: .legal,foodGroup: .vegetables, description: "W/o added sugars, etc."),
    Food(name: "Dried milk solids", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Drumsticks", allowed: .illegal, foodGroup: .vegetables, description: "No okra (bhindi) or drumsticks. Since they are a mucilaginous food, they are illegal."),
    Food(name: "Dry curd cottage cheese",allowed: .legal, foodGroup: .dairy, description: "See BTVC website for sources."),
    Food(name: "Durum flour", allowed: .illegal, foodGroup: .grains, description: "Its a type wheat grain flour"),
    Food(name: "Echinacea", allowed: .legal, foodGroup: .miscellaneous, description: "Especially if it is in Alcohol, but even it is in pill form with a bit of lactose. It can be very helpful if a cold or flu is coming on."),
    Food(name: "Edam cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Eggplant", allowed: .legal, foodGroup: .nightshadeVegetables),
    Food(name: "Eggs", allowed: .legal, foodGroup: .animalProteins),
    Food(name: "EMPower", allowed: .illegal, foodGroup: .miscellaneous, description: "Has many Illegal ingredients, Brown Rice Bran, FOS, Bifidus, flax seed"),
    //        Food(name: "Elemental spices", allowed: .legal, foodGroup: .spices, description: "Cinnamon, nutmeg, etc"),
    //        Food(name: "Enzyme treated milk", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Ethanol", allowed: .legal, foodGroup: .miscellaneous, description: "Ethanol is alcohol - the kind in gin, etc."),
    Food(name: "Evaporated cane juice", allowed: .illegal, foodGroup: .sweeteners, description: "Fancy name for sugar"),
    Food(name: "Ezekiel bread", allowed: .illegal, foodGroup: .grains, description: "Sprouted grain breads are illegal."),
    Food(name: "Faba beans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Fenugreek", allowed: .illegal, foodGroup: .herbs),
    Food(name: "Feta cheese", allowed: .illegal, foodGroup: .dairy, description: "Feta may be used after about 6 months of improvement. But used only in small amounts."),
    Food(name: "Figs", allowed: .legal, foodGroup: .fruit, description: "Figs unpolluted by chemicals or additives are fine, however I find them, especially in dried form; to be a laxative. They also contain hundreds of tiny hard seeds which can be hard on the intestines. I'm still unable to tolerate them after almost a year on the SCD™. If I were you I'd leave figs until you've been symptom free for at least a while. - Rob B"),
    Food(name: "Filberts (hazelnuts)", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating. Nuts should only be used as nut flour, in recipes, until diarrhea has subsided."),
    Food(name: "Fish", allowed: .legal, foodGroup: .animalProteins, description: "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
    Food(name: "Flax seed", allowed: .illegal, foodGroup: .nutsAndSeeds, description: "See Flax seed and flax seed oil within the Knowledge Base section of BTVC website"),
    Food(name: "Flax seed oil", allowed: .legal, foodGroup: .miscellaneous, description: "See Flax seed and flax seed oil within the Knowledge Base section of BTVC website."),
    Food(name: "Flour", allowed: .illegal, foodGroup: .grains),
    //        Food(name: "Fluid milk of any kind", allowed: .illegal, foodGroup: .dairy, description: "But can be used in making yoghurt"),
    //        Food(name: "Food glaze", allowed: .illegal, foodGroup: .miscellaneous, description: "Found in supplements"),
    Food(name: "FOS", allowed: .illegal, foodGroup: .miscellaneous, description: "Also known as fructooligosaccharides. See, FOS in the Knowledge Base section of BTVC website."),
    Food(name: "Fowl", allowed: .legal, foodGroup: .animalProteins, description: "All types including turkey, chicken, duck, goose, pheasant, pigeon etc"),
    Food(name: "Frozen orange juice (concentrated)", allowed: .illegal,foodGroup: .drinks, description: "If orange juice is just frozen and has no additives then it is legal, however frozen orange juice is normally concentrated before freezing and the process to concentrate it makes it illegal see frozen orange juice processing on BTVC website"),
    Food(name: "Fructose (granulated)", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Fruits (canned)", allowed: .warning, foodGroup: .fruit, description: "Fruits canned in their own juice are allowed."),
    Food(name: "Garbanzo beans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Garfava flour", allowed: .illegal, foodGroup: .legumes, description: "Made from two types of beans, Garbanzo beans and Fava beans, neither are SCD™ legal."),
    Food(name: "Garlic", allowed: .legal, foodGroup: .vegetables, description: "Use fresh garlic; garlic powders have starch added as anti-caking agents. You may also make your own garlic powder from fresh garlic by dehydrating it and grinding it yourself."),
    //        Food(name: "Garlic powder", allowed: .illegal, foodGroup: .vegetables, description: "Starch base - make home made"),
    Food(name: "Gelatin (unflavored)", allowed: .legal, foodGroup: .animalProteins, description: "It is a denatured protein that has lost its tertiary structure although it is not the best protein."),
    Food(name: "Ghee", allowed: .legal, foodGroup: .dairy, description: "Clarified butter"),
    Food(name: "Gin", allowed: .legal, foodGroup: .drinks, description: "Only have it occasionally."),
    Food(name: "Ginger", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Gjetost cheese", allowed: .illegal, foodGroup: .dairy),
    //        Food(name: "Glucose", allowed: .illegal, foodGroup: .miscellaneous, description: "Although a monosaccharide, they are often packaged with other sugars that aren't on the label"),
    Food(name: "Glucose candy", allowed: .illegal, foodGroup: .miscellaneous, description: "Contains granulated glucose is known to contains other sugars in addition to glucose."),
    Food(name: "Glycerin", allowed: .legal, foodGroup: .additives, description: "Since glycerin is not a sugar to begin with, the \"ol\" at the end does not make it a sugar alcohol. Glycerin is considered to belong to the fat family. So does glycerol."),
    Food(name: "Glycerol", allowed: .legal, foodGroup: .additives, description: "Since glycerin is not a sugar to begin with, the \"ol\" at the end does not make it a sugar alcohol. Glycerin is considered to belong to the fat family. So does glycerol."),
    Food(name: "Goatein", allowed: .illegal, foodGroup: .miscellaneous, description: "It is a Protein powders that contains Bifidobacteria Bifidum. Protein Powders are a bad idea in any case as they're generally oxidized cholesterol - damaged by heat. - Deborah"),
    Food(name: "Gorgonzola cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Gouda cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Granulated glucose", allowed: .illegal, foodGroup: .sweeteners, description: "It is known to contains other sugars in addition to glucose."),
    Food(name: "Grape juice, white or dark", allowed: .legal, foodGroup: .drinks, description: "White or dark grape juice is allowed. We use Welch's bottled grape juice, as it has been checked out and does not have sugar added. Avoid frozen grape juice, it usually has sugar added. Juice should be diluted with water before drinking."),
    Food(name: "Grapefruit", allowed: .legal,foodGroup: .fruit),
    Food(name: "Grapefruit juice", allowed: .legal, foodGroup: .drinks, description: "Only legal if fresh. Frozen, or canned grapefruit juice is not allowed. Juice should be diluted with water before drinking."),
    Food(name: "Grapes", allowed: .legal, foodGroup: .fruit),
    Food(name: "Grapeseed oil", allowed: .legal, foodGroup: .fatsAndOils),
    //        Food(name: "Green bean", allowed: .legal, foodGroup: .vegetables, description: "Aka: string bean"),
    Food(name: "Green tea", allowed: .legal, foodGroup: .drinks, description: "Limited to 2 cups per day."),
    Food(name: "Gruyere cheese", allowed: .legal,foodGroup: .dairy),
    Food(name: "Guar gum", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Gums", allowed: .illegal, foodGroup: .miscellaneous, description: "All gums are illegal"),
    Food(name: "Ham", allowed: .warning, foodGroup: .animalProteins, description: "Only if cured with salt, it is illegal if cured with sugar dextrose etc see Ham on BTVC website."),
    //        Food(name: "Hard liquor: gin, rye, scotch, bourbon, vodka, etc", allowed: .warning, foodGroup: .drinks, description: "Occasionally"),
    Food(name: "Haricot beans / navy beans", allowed: .legal, foodGroup: .legumes, description: "Dried legumes must be prepared according to the instructions in the book, Breaking the Vicious Cycle."),
    Food(name: "Havarti cheese", allowed: .legal, foodGroup: .dairy, description: "May be used freely."),
    Food(name: "Hazelnuts (filberts)",allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating. Nuts should only be used as nut flour, in recipes, until diarrhea has subsided."),
    Food(name: "Hemp seed, hemp protein powder", allowed: .illegal, foodGroup: .nutsAndSeeds),
    Food(name: "HN-Zyme", allowed: .legal, foodGroup: .miscellaneous),
    Food(name: "Homemade yoghurt", allowed: .legal, foodGroup: .dairy, description: "See BTVC website"),
    Food(name: "Honey", allowed: .legal, foodGroup: .sweeteners),
    Food(name: "Horseradish sauce", allowed: .warning, foodGroup: .sauces, description: "If homemade, if manufactured only if you know they have not added illegals"),
    Food(name: "Hot dogs", allowed: .illegal, foodGroup: .animalProteins, description: "Commercially produced hotdogs will normally be illegal but see BTVC website for a legal recipe by Marilyn"),
    Food(name: "Hydrolyzed protein aka: MSG", allowed: .illegal, foodGroup: .additives, description: "Regardless of whether it is SCD™ legal or not, we should all try to avoid it. MSG can be a potent neurotoxin."),
    Food(name: "Ice cream", allowed: .illegal, foodGroup: .dairy, description: "Commercially prepared ice cream is not allowed. However, there are many wonderful recipes for homemade ice cream."),
    Food(name: "Inositol", allowed: .illegal, foodGroup: .miscellaneous, description: "Inositol is a sugar alcohol. Sugar alcohols will feed bacteria and that is something we do not want to do. Sugar alcohols generally cause diarrhea but small amounts in supplements are ok - Elaine"),
    //        Food(name: "Instant soup mixes / bases", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Inulin", allowed: .illegal, foodGroup: .starch, description: "Inulin is a FOS and is illegal"),
    Food(name: "Iron supplements", allowed: .illegal, foodGroup: .miscellaneous, description: "Please do not get vitamins with iron; they encourage all kinds of infections especially in the gut, and iron has had much research done on it re other diseases. No oral iron if you can help it. Just eat the liver pate and if you like liver, eat it at least once a week."),
    Food(name: "Isoglucose", allowed: .illegal, foodGroup: .sweeteners, description: "It is a new sweetner likely to be used in many products in future."),
    Food(name: "Jaggery (gur)", allowed: .illegal, foodGroup: .sweeteners),
    Food(name: "Jalapenos", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Jicama", allowed: .illegal, foodGroup: .vegetables),
    Food(name: "Juice from concentrate", allowed: .illegal, foodGroup: .drinks, description: "Juice from concentrate is normally illegal because when it is reconstituted they often add other things (like sugar). Often additives are not listed on the label"),
    //        Food(name: "Kala chana - small chickpea w/ brown skin", allowed: .illegal, foodGroup: .legumes, description: "Aka: chickpea, ceci bean, bengal gram, hummus, chana, channa"),
    Food(name: "Kale", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Kefir", allowed: .illegal, foodGroup: .dairy, description: "See BTVC website."),
    Food(name: "Ketchup", allowed: .illegal, foodGroup: .sauces, description: "Commercially prepared ketchup contains sugar and is not allowed. See the gourmet section of the book, Breaking the Vicious Cycle for a ketchup recipe."),
    Food(name: "Kidney beans", allowed: .legal, foodGroup: .legumes, description: "(All Types) May be tried when symptom free. Dried legumes must be prepared according to the instructions in the book, Breaking the Vicious Cycle."),
    Food(name: "Kimchi", allowed: .legal, foodGroup: .vegetables, description: "Knowledge Base section of BTVC website."),
    Food(name: "Kiwi fruit", allowed: .legal, foodGroup: .fruit),
    Food(name: "Kohlrabi", allowed: .illegal, foodGroup: .vegetables, description: "Knowledge Base section of BTVC website."),
    Food(name: "Konjac", allowed: .illegal, foodGroup: .miscellaneous, description: "Also called  konjaku, konnyaku, or the konnyaku potato, or elephant yam. The dried corm of the konjac plant contains around 40% glucomannan gum. See BTVC website."),
    Food(name: "Kudzu (or kuzu)", allowed: .illegal,foodGroup: .miscellaneous, description: "It is a mucilaginous herb. Mucilaginous herbs are loaded with starch. This starch is food for the pathogens that the SCD™ is designed to starve out."),
    Food(name: "Kumquats", allowed: .legal, foodGroup: .fruit),
    Food(name: "KyoGreen powder", allowed: .illegal, foodGroup: .miscellaneous),
    //        Food(name: "L-leucine aka: leucine", allowed: .legal, foodGroup: .miscellaneous, description: "Found in supplements"),
    Food(name: "L-Theanine", allowed: .legal, foodGroup: .miscellaneous, description: "It is an amino acid, as long as its pure without illegal binders, etc its legal, as with any new food go slow introducing it. - Seth"),
    Food(name: "Lactaid milk", allowed: .illegal, foodGroup: .dairy, description: "The rate of flow of galactose to the liver when one drinks lactose hydrolyzed milk is high. With lactose hydrolyzed milk, you are ingesting the two sugars: glucose and galactose at the same time. Note: Lactaid Milk is Lactose Hydrolyzed Milk"),
    Food(name: "Lactose Hydrolyzed Milk", allowed: .illegal, foodGroup: .dairy, description: "The rate of flow of galactose to the liver when one drinks lactose hydrolyzed milk is high. With lactose hydrolyzed milk, you are ingesting the two sugars: glucose and galactose at the same time. Note: Lactaid Milk is Lactose Hydrolyzed Milk"),
    Food(name: "Lamb", allowed: .legal, foodGroup: .animalProteins, description: "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
    Food(name: "Lecithin", allowed: .warning, foodGroup: .miscellaneous, description: "Derived from soy (illegal). There is plenty of good lecithin in egg yolks, and Elaine sees no particular need to take it outside of a whole food."),
    Food(name: "Leek", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Lemons", allowed: .legal, foodGroup: .fruit),
    //        Food(name: "Lentil flour", allowed: .illegal,   foodGroup: .legumes, description: "Must be soaked before grinding - bought varieties are not."),
    Food(name: "Lentils", allowed: .legal, foodGroup: .legumes, description: "Dried legumes must be prepared according to the instructions in the book, Breaking the Vicious Cycle."),
    Food(name: "Lettuce", allowed: .legal, foodGroup: .vegetables, description: "(supplement ingredient)"),
    Food(name: "Leucine", allowed: .legal, foodGroup: .miscellaneous, description: "All varieties of lettuce are legal."),
    Food(name: "Licorice", allowed: .illegal, foodGroup: .miscellaneous, description: "Licorice is both a demulcent and a laxative. For more info on demulcents see Demulcents in Knowledge Base section of BTVC website."),
    Food(name: "Lignin", allowed: .illegal, foodGroup: .miscellaneous, description: "Grinding lignin and tough stuff does not prevent certain microorganisms from thanking you for chewing up their nutrition. The little buggers then respond by eating faster and making more babies and toxins."),
    Food(name: "Lima beans", allowed: .legal, foodGroup: .legumes, description: "Dried or fresh are permitted. Dried legumes must be prepared according to the instructions in the book, Breaking the Vicious Cycle."),
    Food(name: "Limburger cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Limes", allowed: .legal, foodGroup: .fruit),
    Food(name: "Liquers", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Liquid clorychlorophyll", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Macadamia nuts", allowed: .legal, foodGroup: .nutsAndSeeds),
    Food(name: "Macadamia oil", allowed: .legal, foodGroup: .fatsAndOils, description: "Makes the best tasting mayo - Deborah.  Withstands heat well"),
    Food(name: "Magnesium citrate", allowed: .legal, foodGroup: .miscellaneous, description: "As a supplement ingredient"),
    Food(name: "Magnesium stearate", allowed: .legal, foodGroup: .miscellaneous, description: "As a supplement ingredient"),
    Food(name: "Malitol", allowed: .illegal, foodGroup: .sweeteners, description: "Sorbitol, mannitol, and xylitol are all sugar alcohols and are not SCD™ legal. They fall under the category of indigestible carbs and sugars, and so allow companies to label things 'sugar free', even though they are providing nutrition to the bacteria that live in your digestive tract."),
    Food(name: "Maltodextrin", allowed: .illegal, foodGroup: .additives, description: "Maltodextrin is the worst of the small molecules of sugars. It is a very short chain of glucose molecules (derived from starch). The chances of digestion are practically nil. It therefore will feed bacteria and because of its particular structure, Elaine feels it is worse than even lactose."),
    Food(name: "Manchego cheese", allowed: .legal, foodGroup: .dairy),
    Food(name: "Mangoes", allowed: .legal, foodGroup: .fruit),
    Food(name: "Mannitol", allowed: .illegal, foodGroup: .sweeteners, description: "Sorbitol, mannitol, and xylitol are all sugar alcohols and are not SCD™ legal. They fall under the category of indigestible carbs and sugars, and so allow companies to label things 'sugar free', even though they are providing nutrition to the bacteria that live in your digestive tract."),
    Food(name: "Maple syrup", allowed: .illegal, foodGroup: .sweeteners, description: "Maple syrup is a disaccharide."),
    Food(name: "Margarine", allowed: .illegal, foodGroup: .fatsAndOils),
    Food(name: "Marshmallow", allowed: .illegal, foodGroup: .herbs, description: "It is a mucilaginous herb. Mucilaginous herbs are loaded with starch. This starch is food for the pathogens that the SCD™ is designed to starve out."),
    Food(name: "Mastic gum", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Mead - homemade", allowed: .legal, foodGroup: .drinks, description: "If homemade and ingredients are honey and yeast, commercial is likely to have sugar added and is illegal"),
    Food(name: "Meats", allowed: .legal, foodGroup: .animalProteins, description: "All fresh or frozen meats with no additives or processing are legal including beef, lamb, pork, liver, kidney, oxtail and tongue"),
    Food(name: "Meats (canned)", allowed: .illegal, foodGroup: .animalProteins),
    Food(name: "Meats (processed)", allowed: .illegal, foodGroup: .animalProteins, description: "Most have additives such as starch, lactose and sugar e.g. hot dogs, turkey loaf, spiced ham, bologna, smoked meats."),
    Food(name: "Melatonin", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Melon",   allowed: .legal, foodGroup: .fruit, description: "All types are Legal"),
    //        Food(name: "Methyl cellulose", allowed: .legal, foodGroup: .miscellaneous, description: "Found in supplements"),
    //        Food(name: "Microcrystalline cellulose", allowed: .legal, foodGroup: .miscellaneous, description: "Found in supplements"),
    Food(name: "Milk", allowed: .illegal, foodGroup: .dairy, description: "Fluid milk of any kind is not permitted."),
    Food(name: "Millet", allowed: .illegal, foodGroup: .grains),
    Food(name: "Miracle Noodles", allowed: .illegal, foodGroup: .miscellaneous, description: "Made of glucomannan, a  water-soluble polysaccharide.  Glucommanan is obtained from the root of an Asian plant called konjac (full name Amorphophallus konjac). It has been nicknamed the elephant yam, and also called konjaku, konnyaku, or the konnyaku potato."),
    Food(name: "Miso", allowed: .illegal, foodGroup: .miscellaneous),
    //        Food(name: "Mixed nuts", allowed: .illegal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
    Food(name: "Molasses", allowed: .illegal, foodGroup: .sweeteners),
    Food(name: "Molo-cure", allowed: .illegal, foodGroup: .miscellaneous, description: "The main constituent of Molo-cure is aloe. Aloe is not SCD™ compliant as it contains mucilaginous polysaccharides as well as increasing the release of tumor necrosis factor which is associated with IBD inflammation and increased immune stimulation."),
    Food(name: "Montery Jack cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Mozzarella cheese", allowed: .illegal, foodGroup: .dairy),
    Food(name: "MSG", allowed: .illegal, foodGroup: .additives, description: "Regardless of whether it is SCD™ legal or not, we should all try to avoid it. MSG can be a potent neurotoxin."),
    Food(name: "Mucilaginous herbs", allowed: .illegal, foodGroup: .herbs, description: "Slimy, mucilaginous substances are often prescribed as some think the \"coating\" properties are helpful to the intestines. They aren't. We who have compromised guts cannot digest this stuff but our bugs can have quite a party on it."),
    Food(name: "Mucilaginous polysaccharides", allowed: .illegal, foodGroup: .miscellaneous, description: "Slimy, mucilaginous substances are often prescribed as some think the \"coating\" properties are helpful to the intestines. They aren't. We who have compromised guts cannot digest this stuff but our bugs can have quite a party on it."),
    Food(name: "Muenster cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Mungbeans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Mushrooms", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Mustard, plain", allowed: .legal, foodGroup: .sauces, description: "Mustard is legal as long as it doesn't contain illegal ingredients; read the labels carefully."),
    Food(name: "Natural cheeses", allowed: .legal, foodGroup: .dairy, description: "See the appendix of the book, Breaking the Vicious Cycle, for a complete list of allowable cheeses."),
    Food(name: "Natural flavors", allowed: .illegal, foodGroup: .additives, description: "\"Natural flavoring\" can be used to refer to anything, including the chemicals coming from big \"flavor\" companies which sell chemicals to food processors."),
    Food(name: "Navy beans", allowed: .legal, foodGroup: .legumes, description: "Dried legumes must be prepared according to the instructions in the book, Breaking the Vicious Cycle."),
    Food(name: "Nectarines", allowed: .legal, foodGroup: .fruit),
    Food(name: "Nettles", allowed: .illegal, foodGroup: .herbs, description: "Adverse effects from consuming nettle tea can range from upset stomach to burning sensations in the skin, difficulty in urination and bloating."),
    Food(name: "Neufchatel cheese", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Noni juice", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Nutmeg", allowed: .legal, foodGroup: .spices),
    Food(name: "Oats", allowed: .illegal, foodGroup: .grains),
    Food(name: "Okra", allowed: .illegal, foodGroup: .vegetables, description: "No okra (bhindi) or drumsticks, since they are a mucilaginous food, they are illegal."),
    Food(name: "Olive oil", allowed: .legal, foodGroup: .fatsAndOils, description: "Olive oil withstands heat well, good for frying cookng and is highly recommended."),
    Food(name: "Olives", allowed: .legal, foodGroup: .fruit, description: "Olives are legal as long as they do not contain illegal ingredients; read the labels carefully."),
    Food(name: "Onion powder", allowed: .illegal, foodGroup: .spices, description: "Starch base - make home made"),
    Food(name: "Onions", allowed: .legal, foodGroup: .vegetables, description: "Use fresh onions. Onion powders have starch added as anti-caking agents. You may also make your own onion powder from fresh onions by dehydrating them and grinding them yourself"),
    Food(name: "Orange juice", allowed: .legal, foodGroup: .drinks, description: "Fresh orange juice that does not have sugar added is allowed. While diarrhea is active, avoid having orange juice in the morning. We use Tropicana's Original Orange Juice, as it has been checked out and does not have sugar added."),
    Food(name: "Oranges", allowed: .legal, foodGroup: .fruit),
    Food(name: "Oregano", allowed: .legal, foodGroup: .herbs),
    Food(name: "Papayas", allowed: .legal, foodGroup: .fruit),
    Food(name: "Pappadum", allowed: .illegal, foodGroup: .legumes, description: "They are an Indian snack made from lentils - they're like a chip. Also contains rice flour"),
    Food(name: "Paprika", allowed: .legal, foodGroup: .spices),
    Food(name: "Parmesan cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Parsley", allowed: .legal, foodGroup: .herbs),
    Food(name: "Parsnips", allowed: .illegal, foodGroup: .vegetables, description: "At one time, I had them included in my book but after getting feedback from the inflammatory bowel listserv, I took them off. Some children do well with them; others do not. However, they are pretty good from a carb standpoint and Dr. Haas allowed them. - Elaine"),
    Food(name: "Passion fruit", allowed: .legal, foodGroup: .fruit),
    Food(name: "Pasta", allowed: .illegal, foodGroup: .grains),
    Food(name: "Pau 'Arco", allowed: .illegal, foodGroup: .drinks, description: "Bark tea (Pau d'Arco) contains steroidal saponins and is both an immune booster and a laxative."),
    Food(name: "Pea flour", allowed: .illegal, foodGroup: .vegetables),
    Food(name: "Peaches", allowed: .legal, foodGroup: .fruit),
    Food(name: "Peanut butter", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Natural peanut butter with no sugar added is allowed."),
    Food(name: "Peanut oil", allowed: .legal, foodGroup: .fatsAndOils),
    Food(name: "Peanuts", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Peanuts in the shell may be tried cautiously after 6 months on the diet if diarrhea is gone. Shelled peanuts are illegal. Nuts sold in mixtures are not allowed, as most are roasted with a starch coating."),
    Food(name: "Pears", allowed: .legal, foodGroup: .fruit),
    Food(name: "Peas", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Pecans", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating. Nuts should only be used as nut flour, in recipes, until diarrhea has subsided."),
    Food(name: "Pectin", allowed: .illegal, foodGroup: .miscellaneous, description: "It is a polysaccharide which, in the presence of acid and sugar, gels. It is used as a thickener in jams, and occurs naturally in some fruit, like apples. In apples, it's mostly in the peel, and for someone beginning the diet, you normally wouldn't get too much from eating an apple, because you'd peel it. Pectin as an added ingredient is not legal, as it is a complex sugar."),
    Food(name: "Peppermint tea", allowed: .legal, foodGroup: .drinks, description: "Some brands out there put in natural flavourings which would make them illegal, so check the ingredients carefully - Charlene"),
    Food(name: "Peppers / capsicum", allowed: .legal, foodGroup: .nightshadeVegetables, description: "Green, yellow, and red peppers are permitted. Also jalapeno peppers, habanera peppers, chili peppers, poblano peppers, relleno peppers, etc. are legal."),
    Food(name: "Peptizyde", allowed: .legal, foodGroup: .miscellaneous),
    Food(name: "Persimmons", allowed: .legal, foodGroup: .fruit),
    Food(name: "Phosphatidylcholine", allowed: .legal, foodGroup: .miscellaneous, description: "Another name for lecithin which is legal. Eggs have a huge amount of this but if you are not eating eggs, perhaps a bit of supplement is fine. - Elaine"),
    Food(name: "Pickles (dill)", allowed: .legal, foodGroup: .vegetables, description: "Dill pickles are legal as long as they do not contain illegal ingredients; read the labels carefully. See BTVC website for a recipe."),
    Food(name: "Pine nuts", allowed: .warning, foodGroup: .nutsAndSeeds, description: "They are very hard to digest and even grinding them for pesto doesn't make them any easier on your gut. May be tried in small amounts after symptoms have subsided."),
    Food(name: "Pineapple",   allowed: .legal, foodGroup: .fruit),
    Food(name: "Pineapple juice", allowed: .illegal, foodGroup: .fruit, description: "fall 2010 update: The Dole 100% Pineapple juice in the can now adds Vitamins A, C and E. The Vitamin A is bound with cornstarch.\nold info: Fresh pineapple juice that does not have sugar added is allowed. We use Dole's unsweetened pineapple juice in the can, as it has been checked out and does not have sugar added. Juice should be diluted with water before drinking."),
    Food(name: "Pinto beans", allowed: .illegal, foodGroup: .legumes, description: "Even after soaking they have the wrong kind of starch"),
    Food(name: "Pistachio nuts", allowed: .legal, foodGroup: .nutsAndSeeds, description: "They are legal, but the skins can be really tough for newbies. And don't get the pink dyed ones, or the salted ones because they can have starch added to them. You can get unsalted, unroasted pistachios at the health food store and then roast them yourself. For instructions see, Pistachio Nuts in Knowledge Base section of BTVC website."),
    //        Food(name: "Plant cellulose", allowed: .legal, foodGroup: .miscellaneous, description: "Found in supplements"),
    Food(name: "Plantains", allowed: .illegal, foodGroup: .miscellaneous, description: "They contain too much starch."),
    Food(name: "Plums", allowed: .legal, foodGroup: .fruit),
    Food(name: "Polysorbate 80", allowed: .illegal, foodGroup: .miscellaneous, description: "See Knowledge Base section of BTVC website"),
    Food(name: "Pomegranate concentrate", allowed: .illegal, foodGroup: .fruit),
    Food(name: "Pork", allowed: .legal, foodGroup: .animalProteins, description: "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
    Food(name: "Pork rinds", allowed: .legal, foodGroup: .animalProteins, description: "Use the plain pork rinds with no added flavourings and check the label carefully to make sure they don't contain illegal ingredients"),
    Food(name: "Port du salut cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Port wine", allowed: .illegal, foodGroup: .drinks, description: "Its full of sugar"),
    Food(name: "Postum", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Potassium sorbate", allowed: .legal, foodGroup: .miscellaneous, description: "Supplement ingredient"),
    Food(name: "Potatoes", allowed: .illegal, foodGroup: .starch, description: "Both white and sweet potatoes are illegal."),
    Food(name: "Poultry", allowed: .legal, foodGroup: .animalProteins, description: "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
    Food(name: "Primal Defense", allowed: .illegal, foodGroup: .miscellaneous, description: "See Knowledge Base section of BTVC website"),
    Food(name: "Primost cheese", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Processed cheese", allowed: .illegal, foodGroup: .dairy, description: "See the appendix of the book, Breaking the Vicious Cycle, for a complete list of illegal cheeses."),
    Food(name: "Protein powder", allowed: .illegal, foodGroup: .miscellaneous, description: "See Knowledge Base section of BTVC website"),
    Food(name: "Provolone cheese", allowed: .legal, foodGroup: .dairy, description: "Although not listed with the other cheeses on page 140 of Breaking the Vicious Cycle, provolone cheese is legal."),
    Food(name: "Prunes", allowed: .legal, foodGroup: .fruit),
    Food(name: "Psyllium husks", allowed: .illegal, foodGroup: .miscellaneous, description: "They are loaded with cellulose and lignin which some bacteria thrive on. We accept that the cellulose in vegetables and fruit can be handled OK but a concentrated form such as husks would not be in order."),
    Food(name: "Pumpkin", allowed: .legal, foodGroup: .vegetables, description: "Fresh pumpkin is legal, canned pumpkin is not allowed. Butternut squash may be used as a substitute for pumpkin in baking."),
    Food(name: "Pumpkin (canned)", allowed: .illegal, foodGroup: .vegetables, description: "Canned pumpkin is illegal. Butternut squash may be substituted for pumpkin in baking."),
    Food(name: "Quinoa", allowed: .illegal, foodGroup: .grains, description: "Since Quinoa is 60% starch, it is very illegal."),
    Food(name: "Quorn", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Raisins", allowed: .warning, foodGroup: .fruit, description: "Try them cautiously."),
    //        Food(name: "Raw cashews", allowed: .legal, foodGroup: .fruit, description: "Mixes not allowed"),
    Food(name: "Rhubarb", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Rice", allowed: .illegal, foodGroup: .grains, description: "Both brown and white rice are illegal."),
    Food(name: "Rice bran", allowed: .illegal, foodGroup: .grains, description: "Except as a supplement filler as it is mainly oil. If one is taking a supplement which has proven to be efficacious, then the small amount of filler within the supplement will probably not have an adverse effect. - Elaine."),
    Food(name: "Rice flour", allowed: .illegal, foodGroup: .grains),
    Food(name: "Ricotta cheese", allowed: .illegal, foodGroup: .dairy),
    //        Food(name: "Roasted peanuts in the shell", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Shelled / mixes are illegal"),
    Food(name: "Romano cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Roquefort cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "Rosemary", allowed: .legal, foodGroup: .herbs),
    Food(name: "Rutabaga", allowed: .legal, foodGroup: .vegetables, description: "Also known as swede It is very fibrous, so go slow and be careful."),
    //        Food(name: "Rye (the drink)", allowed: .legal, foodGroup: .drinks, description: "Occasionally"),
    Food(name: "Rye", allowed: .illegal, foodGroup: .grains),
    Food(name: "Saccharin", allowed: .legal, foodGroup: .sweeteners),
    Food(name: "Safflower oil", allowed: .legal, foodGroup: .fatsAndOils),
    Food(name: "Sage", allowed: .legal, foodGroup: .herbs),
    Food(name: "Sago starch", allowed: .illegal, foodGroup: .starch),
    Food(name: "Sake", allowed: .illegal, foodGroup: .drinks, description: "It is not a distilled spirit like Vodka and it is the distillation that removes the illegals - Seth\nBoth sweet and dry sake still have sugar and actually the dry sake has more sugar than the sweet sake but you can't taste it because of the acidity. - Kim"),
    Food(name: "Salt", allowed: .legal, foodGroup: .miscellaneous, description: "Ordinary iodized table salt, altho it sometimes has dextrose, is legal because it is important to get that iodine"),
    Food(name: "Sashimi", allowed: .legal, foodGroup: .animalProteins, description: "(Japanese sushi-style raw fish served all by itself w/o rice)"),
    Food(name: "Sauerkraut", allowed: .warning, foodGroup: .vegetables, description: "Only for advanced SCD'ers"),
    Food(name: "Seaweed", allowed: .illegal, foodGroup: .vegetables, description: "Seaweed is high in polysaccharides and therefore illegal."),
    //        Food(name: "Sausages, commercial", allowed: .illegal, foodGroup: .animalProteins),
    //        Food(name: "Scotch", allowed: .legal, foodGroup: .drinks, description: "Occasionally"),
    Food(name: "Seed butters", allowed: .illegal, foodGroup: .nutsAndSeeds, description: "See Knowledge Base section of BTVC website"),
    Food(name: "Seed flour", allowed: .illegal, foodGroup: .nutsAndSeeds, description: "It is not allowed because the quantity of the flour way surpasses the few seeds that Elaine had in mind when she said \"seeds are permissible after 3 months of no symptoms.\""),
    Food(name: "Seeds", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Permissible after 3 months of no symptoms."),
    Food(name: "Sesame oil", allowed: .legal, foodGroup: .fatsAndOils),
    Food(name: "Sesame seeds", allowed: .legal, foodGroup: .nutsAndSeeds, description: "See Knowledge Base section of BTVC website"),
    Food(name: "Sharifa", allowed: .legal, foodGroup: .fruit, description: "Also known as custard apple or cherimoya"),
    Food(name: "Shellfish", allowed: .legal, foodGroup: .animalProteins, description: "Fresh and frozen are allowed as long as nothing has been added during processing; check the labels carefully."),
    Food(name: "Sherry", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Silica", allowed: .legal, foodGroup: .miscellaneous, description: "(supplement ingredient)"),
    Food(name: "Silicon dioxide", allowed: .legal, foodGroup: .miscellaneous, description: "(supplement ingredient)"),
    //        Food(name: "Silvia seed a.k.a., silvia hispanica, chia seeds", allowed: .illegal, foodGroup: .nutsAndSeeds, description: "Mucilaginous"),
    Food(name: "Slippery elm", allowed: .illegal, foodGroup: .miscellaneous, description: "It is a mucilaginous herb. Mucilaginous herbs are loaded with starch. This starch is food for the pathogens that the SCD™ is designed to starve out."),
    Food(name: "Smoked meats", allowed: .illegal, foodGroup: .animalProteins, description: "Unless you know with certainty that no sugar has been added during the smoking process, they are not permitted."),
    Food(name: "Sodium benzoate", allowed: .legal, foodGroup: .miscellaneous, description: "(supplement ingredient)"),
    Food(name: "Sodium starch glycinate", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Sorbitol", allowed: .illegal, foodGroup: .sweeteners, description: "Sorbitol, mannitol, and xylitol are all sugar alcohols and are not SCD™ legal. They fall under the category of indigestible carbs and sugars, and so allow companies to label things 'sugar free', even though they are providing nutrition to the bacteria that live in your digestive tract."),
    Food(name: "Sour cream", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Soy", allowed: .illegal, foodGroup: .legumes, description: "See Soy in the Knowledge Base section of BTVC website"),
    Food(name: "Soy lecithin", allowed: .illegal, foodGroup: .additives, description: "Derived from soy (illegal). There is plenty of good lecithin in egg yolks, and Elaine sees no particular need to take it outside of a whole food. Also see Carlsons fish oil in the Knowledge Base section of BTVC website."),
    Food(name: "Soy sauce", allowed: .illegal, foodGroup: .sauces, description: "Soy sauce is a fermented soy product and also contains wheat so it is illegal."),
    Food(name: "Soybean milk", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Soybean oil", allowed: .illegal, foodGroup: .fatsAndOils),
    Food(name: "Soybeans", allowed: .illegal, foodGroup: .legumes),
    Food(name: "Spearmint Tea", allowed: .legal, foodGroup: .drinks),
    //        Food(name: "Sparkling water a.k.a. seltzer water", allowed: .legal, foodGroup: .drinks, description: "Ingredients: only carbonated water"),
    Food(name: "Spelt", allowed: .illegal, foodGroup: .grains),
    Food(name: "Spices", allowed: .legal, foodGroup: .spices, description: "Spices of all kinds may be used, but avoid spice mixtures; buy spices separately."),
    Food(name: "Spinach", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Spirulina", allowed: .illegal, foodGroup: .miscellaneous, description: "We do not use algae (Spirulina) because IBD involves the immune system and can aggravate an already disturbed immune system."),
    Food(name: "Splenda", allowed: .illegal, foodGroup: .sweeteners, description: "There are several reasons why it is illegal, see Knowledge Base section of BTVC website"),
    Food(name: "Split peas", allowed: .legal, foodGroup: .legumes, description: "Dried legumes must be prepared according to the instructions in the book, Breaking the Vicious Cycle."),
    //        Food(name: "Sports drinks", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Sprouted grain bread", allowed: .illegal, foodGroup: .grains),
    Food(name: "Squash", allowed: .legal, foodGroup: .vegetables, description: "Both winter and summer squashes are legal."),
    //        Food(name: "Starches of any kind", allowed: .illegal, foodGroup: .starch),
    Food(name: "Stevia", allowed: .illegal, foodGroup: .sweeteners, description: "Its molecular structure resembles a steroid and the effects are unknown. See Knowledge Base section of BTVC website."),
    Food(name: "Stilton cheese", allowed: .legal, foodGroup: .dairy, description: "May be used occasionally."),
    Food(name: "String beans / green beans", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Sucralose", allowed: .illegal, foodGroup: .sweeteners, description: "There are several reasons why it is illegal, see Splenda in Knowledge Base section of BTVC website."),
    //        Food(name: "Sugar", allowed: .illegal,  foodGroup: .sweeteners, description: "Aka: table sugar, white sugar, refined sugar, evaporated cane juice."),
    Food(name: "Sulphates", allowed: .legal, foodGroup: .miscellaneous, description: "When a fruit such as peaches (dried) and coconut is sulphated, it means it has been exposed to sulphur to keep the color from darkening. Some people are allergic to sulphated products but most of us are not bothered by them."),
    Food(name: "Sunflower oil", allowed: .legal, foodGroup: .fatsAndOils),
    Food(name: "Swede / rutabaga", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Sweet potatoes", allowed: .illegal, foodGroup: .starch),
    Food(name: "Swiss cheese", allowed: .legal, foodGroup: .dairy, description: "May be used freely."),
    Food(name: "Tabasco sauce", allowed: .legal, foodGroup: .sauces, description: "Only the original red Tabasco sauce, labeled \"McIlhenny Company Tabasco Brand Pepper Sauce\" is legal but as with all manufactured products check the ingredients. The other Tabasco styles all have sugars and gums added."),
    Food(name: "Tagatose", allowed: .illegal, foodGroup: .sweeteners),
    //        Food(name: "Tahini - aka: sesame seed butter", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Allowed after 3 months of no symptoms"),
    Food(name: "Tamari", allowed: .illegal, foodGroup: .sauces, description: "It is made from soy"),
    Food(name: "Tamarind", allowed: .illegal, foodGroup: .fruit, description: "See Knowledge Base section of BTVC website."),
    Food(name: "Tangerines",allowed: .legal, foodGroup: .fruit),
    Food(name: "Tapioca", allowed: .illegal, foodGroup: .starch, description: "It is a starch, therefore illegal."),
    Food(name: "Tapioca flour", allowed: .illegal, foodGroup: .starch),
    //        Food(name: "Tapioca starch", allowed: .illegal, foodGroup: .starch),
    Food(name: "Taro", allowed: .illegal, foodGroup: .starch, description: "It has much too much starch in it and is very similar to potatoes."),
    Food(name: "Tarragon", allowed: .legal, foodGroup: .herbs),
    Food(name: "Tea", allowed: .legal, foodGroup: .drinks, description: "\t\n" +
        "Ordinary black tea is legal but should be made weak.\n" +
        "Instant tea,Ojibwa tea (Essiac), many herbal teas, teas made from bark etc are full of polysaccharides and are illegal. Peppermint and spearmint herb teas are legal, and you can make a tea from ginger which is also legal."),
    //        Food(name: "Tea, green", allowed: .legal, foodGroup: .drinks, description: "Limited to 2 cups / day"),
    //        Food(name: "Tea, instant", allowed: .illegal, foodGroup: .drinks),
    //        Food(name: "Tea, peppermint", allowed: .legal, foodGroup: .drinks, description: "Read label"),
    //        Food(name: "Tea, spearmint", allowed: .legal, foodGroup: .drinks),
    //        Food(name: "Tea, weak", allowed: .legal, foodGroup: .drinks,  "Ordinary black tea is allowed but should be made weak. Instant tea, Ojibwa tea (Essiac), many herbal teas, teas made from bark etc., are illegal. Peppermint and spearmint herb teas are allowed, as well as home made ginger tea."),
    //        Food(name: "Teas, herbal", allowed: .illegal, foodGroup: .drinks, description: "Tend to be laxative"),
    Food(name: "Thyme", allowed: .legal, foodGroup: .herbs),
    Food(name: "Tofu", allowed: .illegal, foodGroup: .miscellaneous, description: "It is made from soy"),
    Food(name: "Tofutti cheese", allowed: .illegal, foodGroup: .dairy),
    Food(name: "Tomato", allowed: .legal, foodGroup: .nightshadeVegetables),
    Food(name: "Tomato juice (canned)", allowed: .legal, foodGroup: .nightshadeVegetables, description: "Should only have salt added. Also see Knowledge Base section of BTVC website."),
    //        Food(name: "Tomato juice mixtures", allowed: .illegal, foodGroup: .drinks),
    Food(name: "Tomato paste (canned)", allowed: .illegal, foodGroup: .nightshadeVegetables),
    Food(name: "Tomato puree (canned)", allowed: .illegal, foodGroup: .nightshadeVegetables),
    Food(name: "Tomato sauce (canned)", allowed: .illegal, foodGroup: .sauces),
    Food(name: "Triticale", allowed: .illegal, foodGroup: .grains),
    Food(name: "Turbinado", allowed: .illegal, foodGroup: .sweeteners, description: "It is liquid cane sugar, therefore it is illegal."),
    Food(name: "Turnips", allowed: .illegal, foodGroup: .vegetables, description: "In the most recent printing of BTVC (Ninth Printing - May 2002), turnips were moved from the 'allowed' list to the 'not allowed' list."),
    //        Food(name: "Uncreamed cottage cheese / dry curd cottage cheese", allowed: .legal, foodGroup: .dairy, description: "Freely - not shredded / grated"),
    //        Food(name: "Unflavored gelatin", allowed: .legal, foodGroup: .animalProteins),
    Food(name: "V8 juice", allowed: .illegal, foodGroup: .drinks, description: "It has tomato paste listed as an ingredient. Elaine has listed tomato paste as being illegal. It is also made from concentrate and has added sugar."),
    Food(name: "Vanillin", allowed: .legal, foodGroup: .miscellaneous, description: "But not in concentrated form. See Knowledge Base section of BTVC website."),
    //        Food(name: "Vegetable cellulose", allowed: .legal, foodGroup: .miscellaneous, description: "Found in supplements"),
    Food(name: "Vegetable stearate", allowed: .legal, foodGroup: .miscellaneous, description: "I believe that stearate is always a fat (stearic acid) so vegetable stearate would be a fat from some vegetable like coconut, etc. -- Elaine"),
    Food(name: "Vegetables (canned)", allowed: .illegal, foodGroup: .vegetables, description: "Canned vegetables are not permitted; they must either be fresh or frozen."),
    //        Food(name: "Vinegar, apple cider", allowed: .legal, foodGroup: .miscellaneous, description: "Not gourmet as these have added sugars. Must be filtered."),
    //        Food(name: "Vinegar, red or white wine", allowed: .legal, foodGroup: .miscellaneous, description: "Not gourmet as these have added sugars"),
    Food(name: "Vinegar", allowed: .legal, foodGroup: .miscellaneous, description: "Red and white wine vinegar also white and cider vinegars are allowed but check the label for added illegals. Balsamic vinegar is not allowed as it has added sugar. However you can make your own legal balsamic vinegar substitute see scdrecipe.com"),
    Food(name: "Vodka", allowed: .legal, foodGroup: .drinks, description: "Only have it occasionally."),
    Food(name: "Walnut oil", allowed: .legal, foodGroup: .fatsAndOils, description: "Doesn't withstand heat very well"),
    Food(name: "Walnuts", allowed: .legal, foodGroup: .nutsAndSeeds, description: "Nuts sold in mixtures are not allowed, as most are roasted with a starch coating. Nuts should only be used as nut flour, in recipes, until diarrhea has subsided."),
    Food(name: "Wasabi", allowed: .legal, foodGroup: .spices, description: "As long as it is in its natural state and hasn't had fillers added by a manufacturer "),
    Food(name: "Water chestnuts", allowed: .illegal, foodGroup: .nutsAndSeeds),
    Food(name: "Watercress", allowed: .legal, foodGroup: .vegetables),
    Food(name: "Watermelon", allowed: .legal, foodGroup: .fruit),
    Food(name: "Wheat", allowed: .illegal, foodGroup: .grains),
    Food(name: "Wheat germ", allowed: .illegal, foodGroup: .grains),
    //        Food(name: "Whey, powder or liquid", allowed: .illegal, foodGroup: .dairy, description: "Avoid on GAPS."),
    //        Food(name: "White kidney bean", allowed: .illegal, foodGroup: .legumes, description: "Aka: cannellini, great northern, fazolia"),
    Food(name: "Whisky", allowed: .legal, foodGroup: .drinks, description: "Only have it occasionally."),
    Food(name: "Wine", allowed: .legal, foodGroup: .drinks, description: "Very dry wine is legal. See, Wines for more information on dry wines."),
    Food(name: "Xanthum gum", allowed: .illegal, foodGroup: .miscellaneous),
    Food(name: "Xylitol", allowed: .illegal, foodGroup: .sweeteners, description: "Sorbitol, mannitol, and xylitol are all sugar alcohols and are not SCD™ legal. They fall under the category of indigestible carbs and sugars, and so allow companies to label things 'sugar free', even though they are providing nutrition to the bacteria that live in your digestive tract."),
    Food(name: "Yams", allowed: .illegal, foodGroup: .starch),
    Food(name: "Yoghurt (commercial)", allowed: .illegal, foodGroup: .dairy, description: "Eating commercial yoghurt is not permitted. Commercial yoghurt may be used as a starter for making homemade yoghurt. For directions for making yoghurt, see Knowledge Base section of BTVC website."),
    Food(name: "Yoghurt (homemade)", allowed: .legal, foodGroup: .dairy, description: "See yoghurt in the Knowledge Base section of BTVC website for instructions on how to make legal yoghurt."),
    Food(name: "Yucca root", allowed: .illegal, foodGroup: .miscellaneous)
]
